### PR TITLE
Bumping database-proxy-1.4.3 + other dependency updates

### PR DESCRIPTION
**Pull request by ursjoss**
Hi Vlad

This PR adjusts db-util to the current verison of database-proxy.

On the way I was bumping other dependencies and ignored eclipse specific files.

I have all together 3 feature branches doing all this in dedicated steps. If you prefer to merge them istead of all in one go, just let me know.

Thanks and cheers
Urs

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks, Urs.

**Comment by vladmihalcea** [comment]
Thanks, Urs.

**Comment by ursjoss** [comment]
You're welcome, Vlad. Thanks for the merge and the great utilty. Realy useful!

**Comment by vladmihalcea** [comment]
I'm glad you liked it.

**Pull request merged**
